In [1]:
ls

 Le volume dans le lecteur D s'appelle Data
 Le num‚ro de s‚rie du volume est DC28-9704

 R‚pertoire de D:\GitHub\StrokeLesionPredict-BIO503\PerfusionCT-Net

03/06/2020  02:31    <DIR>          .
03/06/2020  02:31    <DIR>          ..
01/06/2020  12:46             1ÿ985 .gitignore
02/06/2020  15:47    <DIR>          .ipynb_checkpoints
01/06/2020  22:29    <DIR>          configs
01/06/2020  22:29    <DIR>          dataio
01/06/2020  12:46             1ÿ558 journal.md
01/06/2020  22:29    <DIR>          models
02/06/2020  15:57             5ÿ338 Quentin Visual Tools.ipynb
01/06/2020  12:46               998 README.md
02/06/2020  02:37               305 requirements.txt
01/06/2020  22:29    <DIR>          static
02/06/2020  02:35    <DIR>          torchsample
01/06/2020  12:46             6ÿ026 train_segmentation.py
01/06/2020  22:29    <DIR>          utils
               6 fichier(s)           16ÿ210 octets
               9 R‚p(s)  142ÿ978ÿ088ÿ960 octets libres


In [15]:
cd ../

D:\GitHub\StrokeLesionPredict-BIO503


In [40]:
ls

 Le volume dans le lecteur D s'appelle Data
 Le num‚ro de s‚rie du volume est DC28-9704

 R‚pertoire de D:\GitHub\StrokeLesionPredict-BIO503\PerfusionCT-Net

03/06/2020  17:32    <DIR>          .
03/06/2020  17:32    <DIR>          ..
01/06/2020  12:46             1ÿ985 .gitignore
02/06/2020  15:47    <DIR>          .ipynb_checkpoints
01/06/2020  22:29    <DIR>          configs
01/06/2020  22:29    <DIR>          dataio
01/06/2020  12:46             1ÿ558 journal.md
01/06/2020  22:29    <DIR>          models
03/06/2020  17:32           109ÿ096 Quentin Visual Tools.ipynb
01/06/2020  12:46               998 README.md
02/06/2020  02:37               305 requirements.txt
01/06/2020  22:29    <DIR>          static
02/06/2020  02:35    <DIR>          torchsample
01/06/2020  12:46             6ÿ026 train_segmentation.py
01/06/2020  22:29    <DIR>          utils
               6 fichier(s)          119ÿ968 octets
               9 R‚p(s)  142ÿ975ÿ057ÿ920 octets libres


In [39]:
!cd '..\Geneva-Stroke-Preprocessing\visual_tools'
syspath
#import dataset_visualization

Le chemin d'accŠs sp‚cifi‚ est introuvable.


In [14]:
import Geneva-Stroke-Preprocessing.visual_tools

SyntaxError: invalid syntax (<ipython-input-14-8c77a035ff47>, line 1)

In [ ]:
from application.app.folder.file import func_name

In [11]:
ls

 Le volume dans le lecteur D s'appelle Data
 Le num‚ro de s‚rie du volume est DC28-9704

 R‚pertoire de D:\GitHub\StrokeLesionPredict-BIO503\PerfusionCT-Net

03/06/2020  16:18    <DIR>          .
03/06/2020  16:18    <DIR>          ..
01/06/2020  12:46             1ÿ985 .gitignore
02/06/2020  15:47    <DIR>          .ipynb_checkpoints
01/06/2020  22:29    <DIR>          configs
01/06/2020  22:29    <DIR>          dataio
01/06/2020  12:46             1ÿ558 journal.md
01/06/2020  22:29    <DIR>          models
03/06/2020  16:18            22ÿ634 Quentin Visual Tools.ipynb
01/06/2020  12:46               998 README.md
02/06/2020  02:37               305 requirements.txt
01/06/2020  22:29    <DIR>          static
02/06/2020  02:35    <DIR>          torchsample
01/06/2020  12:46             6ÿ026 train_segmentation.py
01/06/2020  22:29    <DIR>          utils
               6 fichier(s)           33ÿ506 octets
               9 R‚p(s)  142ÿ975ÿ574ÿ016 octets libres


In [4]:
import numpy as np

# Load data

In [27]:
brain_masks = np.load('../data/all_2016_2017/brain_masks.npy')
brain_masks

array([[[[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False]],

        [[False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         [False, False, False, ..., False, False, False],
         ...,
         [False, False, False, ..., False, False, False],
         [False, False, Fa

In [25]:
clinical_inputs = np.load('../data/all_2016_2017/clinical_inputs.npy')
clinical_inputs

array([], dtype=float64)

In [26]:
ids = np.load('../data/all_2016_2017/ids.npy')
ids

array(['subj-6ff0284e', 'subj-799c5528', 'subj-7350e686', 'subj-c4e1ba0b',
       'subj-f1938a72', 'subj-2fe16379', 'subj-816ec497', 'subj-ee8c25b5',
       'subj-d73bb537', 'subj-5ca2adc0', 'subj-d6ab787f', 'subj-96beef92',
       'subj-57868c38', 'subj-99cb8a6c', 'subj-363e4c95', 'subj-b34c2105',
       'subj-3ca34c4f', 'subj-906eacdf', 'subj-0cb819df', 'subj-61f13baa',
       'subj-b4ca7c17', 'subj-60c7d944', 'subj-809bbcfc', 'subj-52bbd5f4',
       'subj-5af90b8b', 'subj-8f7e53d1', 'subj-f4197a4d', 'subj-d33e5d47',
       'subj-192974d5', 'subj-f69ae744', 'subj-b5d532f5', 'subj-d78c8166',
       'subj-fb0927e5', 'subj-98711f81', 'subj-ebc36541', 'subj-dcdfb2af',
       'subj-57908a9a', 'subj-37b8094f', 'subj-551fcca4', 'subj-b1a35c04',
       'subj-e3b8457f', 'subj-9b85c60e', 'subj-1fd8218e', 'subj-297da403',
       'subj-25056a5c', 'subj-08de67ba', 'subj-a060c36d', 'subj-6960e00a',
       'subj-5696c474', 'subj-f5ab868e', 'subj-e17fc116', 'subj-df4cc041',
       'subj-56a1e19d', '

In [28]:
included_subjects = np.load('../data/all_2016_2017/included_subjects.npy')
included_subjects

array([], dtype=float64)

In [22]:
params = np.load('../data/all_2016_2017/params.npy')
params

ValueError: Object arrays cannot be loaded when allow_pickle=False

## Heavy data

In [31]:
lesion_GT = np.load('../data/all_2016_2017/lesion_GT.npy')
lesion_GT

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
    

In [32]:
ct_inputs = np.load('../data/all_2016_2017/ct_inputs.npy')
ct_inputs

array([[[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         ...,

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          ...,
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
    